### ISSUE TITLE
model on pandas data set 

### ISSUE THREAD

**Issue by andrewczgithub** [StanfordASL/ALPaCA#2]
Hi @apoorva-sharma 
I would like to use this model on other data sets.
I would like to use this model on time series data on a pandas data set.
I would I structure the model on a multivariate time series data set held in a 
pandas data set.
Many thanks in advance for your help.
Best,
Andrew

**Comment by apoorva-sharma** [comment]
Hi Andrew,

To train this model on a pandas dataset, you would need to create a dataset class similar to [`PresampledDataset`](https://github.com/StanfordASL/ALPaCA/blob/d06391a1bf11beda573078a6a1d62418aac367c4/main/dataset.py#L14) which takes in the pandas dataset rather than numpy arrays.

Then, you can create an object of that class using your pandas dataset, and then run `ALPaCA.train()` as in our examples.

Best,
Apoorva

**Comment by andrewczgithub** [comment]
Hi @apoorva-sharma 
cheers really appreciate the help.
Just a few queries. Im getting an error with imports on the example

multistep-varying-noise.ipynb

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-04889548c60b> in <module>
      3 import numpy as np
      4 import gym
----> 5 from main.maml_agent import MAMLAgent, register_flags
      6 from main.alpaca import *
      7 from main.dataset import *

~/ALPaCA/main/maml_agent.py in <module>
      4 from maml.data_generator import DataGenerator
      5 from tensorflow.python.platform import flags
----> 6 from main.datagen import *
      7 from main.dataViz import *
      8 import yaml

ModuleNotFoundError: No module named 'main.datagen'

Also how do I set up the config file for an external dataset?

Many thanks,
Best,
Andrew
